In [1]:
import numpy as np

initial_nums = np.arange(10_000_000)

initial_nums

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [2]:
%%time

for _ in range(100):
    nums = np.copy(initial_nums)
    
    mask = nums % 2 == 0
    
    vals = nums[mask] * 2
    
    nums[mask] = vals
  
print(nums[:10])

[0 1 2 3 4 5 6 7 8 9]
Wall time: 1.09 s


In [3]:
%%time

for _ in range(100):
    nums = np.copy(initial_nums)
    
    mask = nums % 2 == 0
    
    nums[mask] *= 2
  
print(nums[:10])

[0 1 2 3 4 5 6 7 8 9]
Wall time: 1.16 s


In [4]:
%%time

for _ in range(100):
    nums = np.copy(initial_nums)
    
    nums[nums % 2 == 0] *= 2
  
print(nums[:10])

[0 1 2 3 4 5 6 7 8 9]
Wall time: 1.13 s


In [5]:
%%time

# do not set count above 1
for _ in range(1):
    nums = np.copy(initial_nums)
    for idx, val in np.ndenumerate(nums):
        if val % 2 == 0:
            nums[idx[0]] = val * 2
            
print(nums[:10])

[0 1 2 3 4 5 6 7 8 9]
Wall time: 15 ms


In [7]:
%%time

# do not set count above 5
for _ in range(5):
    nums = np.copy(initial_nums)
    nums = np.vectorize(lambda x: x * 2 if x % 2 == 0 else x)(nums)
    
print(nums[:10])

[ 0  1  4  3  8  5 12  7 16  9]
Wall time: 10.5 s
