In [1]:
import numpy as np

In [2]:
nums = np.arange(10)

nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
new_nums = nums + 5

print(nums)
print(new_nums)

[15 16 17 18 19 20 21 22 23 24]
[20 21 22 23 24 25 26 27 28 29]


In [16]:
old_nums = nums
new_nums = nums + 5
nums = nums + 5

print(nums)
print(new_nums)

print(id(nums))
print(id(new_nums))
print(id(nums) == id(new_nums))
print(id(old_nums) == id(nums))

[20 21 22 23 24 25 26 27 28 29]
[20 21 22 23 24 25 26 27 28 29]
2710514890480
2710514891536
False
False


In [14]:
old_nums = nums
print(id(old_nums) == id(nums))
print(nums)

nums += 5
print(id(old_nums) == id(nums))
print(nums)

True
[10 11 12 13 14 15 16 17 18 19]
True
[15 16 17 18 19 20 21 22 23 24]


In [17]:
new_nums = nums - 5

new_nums

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
new_nums = nums * 5

new_nums

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [19]:
new_nums = nums / 5

new_nums

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8])