In [1]:
import numpy as np

In [11]:
nums = np.arange(5, dtype=np.int8)

nums

array([0, 1, 2, 3, 4], dtype=int8)

In [17]:
nums.append(5)

print(id(nums) == id(new_nums))
new_nums

new_nums[2] = 100000000000000000000

new_nums

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
new_nums = np.concatenate([ nums, [5], [6,7,8], [9,10]])

print(id(nums) == id(new_nums))
new_nums

False


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
new_nums = np.insert(nums, 2, 9)

print(id(nums) == id(new_nums))
new_nums

False


array([0, 1, 9, 2, 3, 4])