In [1]:
import numpy as np

In [2]:
nums = np.arange(10,20)
nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
nums[nums > 14]

array([15, 16, 17, 18, 19])

In [4]:
gt14 = nums > 14

print(gt14)

nums[gt14]

[False False False False False  True  True  True  True  True]


array([15, 16, 17, 18, 19])

In [5]:
nums[ [True, False, False, True, False,  True,  True,  False,  True,  True] ]

array([10, 13, 15, 16, 18, 19])

In [6]:
new_nums = nums[gt14] * -1

new_nums

array([-15, -16, -17, -18, -19])

In [7]:
new_nums[2]

-17

In [8]:
new_nums[ [ 2, 3 ] ]

array([-17, -18])

In [9]:
new_nums[2] = 999

new_nums

array([-15, -16, 999, -18, -19])

In [10]:
new_nums[ [ 2, 3 ] ] = 1000

new_nums

array([ -15,  -16, 1000, 1000,  -19])

In [11]:
nums = np.arange(10,20)

nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
#print(nums[nums > 14] * 2)
#print(nums[nums > 14])

old_nums = nums

# all three are updating the original array

# less efficient because of calculating "nums > 14" twice
nums[nums > 14] = nums[nums > 14] * 2

# more efficient because of calculating "nums > 14" once
# gt14 = nums > 14
# nums[gt14] =  nums[gt14] * 2

# same efficiency as the previous
# nums[gt14] *= 2

print(id(old_nums) == id(nums))
nums

True


array([10, 11, 12, 13, 14, 30, 32, 34, 36, 38])

In [13]:
nums = np.arange(36)

matrix_nums = nums.reshape(6,6)

print(id(nums) == id(matrix_nums))

nums[0] = 1000

print(nums)
print(matrix_nums)

print(nums.shape)
print(matrix_nums.shape)


False
[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35]
[[1000    1    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]
 [  24   25   26   27   28   29]
 [  30   31   32   33   34   35]]
(36,)
(6, 6)


In [14]:
matrix_nums[1]

array([ 6,  7,  8,  9, 10, 11])

In [15]:
matrix_nums[1, 3] # 1 = row, 3 = col

9

In [16]:
nums = matrix_nums[1]

In [17]:
nums[1:3]

array([7, 8])

In [19]:
 matrix_nums[1:3]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [20]:
 matrix_nums[:]

array([[1000,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

In [21]:
 matrix_nums[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [22]:
 matrix_nums[:,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

In [23]:
 matrix_nums[1:5,2:4]

array([[ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27]])

In [24]:
 matrix_nums[1:5:2,2:4]

array([[ 8,  9],
       [20, 21]])