In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3], dtype=np.int8)

arr2 = np.array([4,5,6], dtype=np.int8)

arr3 = np.array([7,8], dtype=np.int8)

In [3]:
print(arr1.shape)
print(arr2.shape)

(3,)
(3,)


In [4]:
arr1 + arr2

array([5, 7, 9], dtype=int8)

In [5]:
print(arr1.shape)
print(arr3.shape)

(3,)
(2,)


In [6]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [8]:
arr4 = arr3[:, np.newaxis]

arr4

array([[7],
       [8]], dtype=int8)

In [9]:
print(arr1.shape)
print(arr4.shape)

(3,)
(2, 1)


In [10]:
print(arr1)
print(arr4)

[1 2 3]
[[7]
 [8]]


In [11]:
arr1 + arr4

array([[ 8,  9, 10],
       [ 9, 10, 11]], dtype=int8)

In [12]:
arr1 - arr4

array([[-6, -5, -4],
       [-7, -6, -5]], dtype=int8)

In [13]:
arr1 * arr4

array([[ 7, 14, 21],
       [ 8, 16, 24]], dtype=int8)

In [15]:
r = arr1 / arr4

print(r.dtype)
r

float64


array([[0.14285714, 0.28571429, 0.42857143],
       [0.125     , 0.25      , 0.375     ]])

In [20]:
np.dot([5,4], [6,3])

42

In [24]:
print(np.array([5,7]))
print(np.array([[6],[8]]))

np.dot([5,7,4,5], [[6],[8]])

[5 7]
[[6]
 [8]]


ValueError: shapes (4,) and (2,1) not aligned: 4 (dim 0) != 2 (dim 0)